#Makefie for 2.6
obj-m += hellomod.o					#模块名字,目标文件
CURRENT_PATH:=$(shell pwd) 			#模块所在的当前路径
LINUX_KERNEL:=$(shell uname -r) 	#Linux内核源代码的当前版本
LINUX_KERNEL_PATH:=/usr/src/linux-headers-$(LINUX_KERNEL)	#内核代码的绝对路径
all:
make -C $(LINUX_KERNEL_PATH)M=$(CURRENT_PATH)modules	#编译之 
clean:
make -C $(LINUX_KERNEL_PATH)M=$(CURRENT_PATH)clean		#清理

